using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Microsoft.ServiceBus.Messaging;

public sealed class ExceptionReceivedEventArgs : EventArgs
{
    //
    // Summary:
    //     Gets the parent class exception to which this event data belongs.
    //
    // Value:
    //     The exception, generated by the parent class, to which this event data belongs.
    public Exception Exception
    {
        get;
        private set;
    }

    //
    // Summary:
    //     Gets the action associated with the event.
    //
    // Value:
    //     The action associated with the event.
    public string Action
    {
        get;
        private set;
    }

    //
    // Summary:
    //     Initializes a new instance of the Microsoft.ServiceBus.Messaging.ExceptionReceivedEventArgs
    //     class.
    //
    // Parameters:
    //   exception:
    //     The exception that this event data belongs to.
    //
    //   action:
    //     The action associated with the event.
    public ExceptionReceivedEventArgs(Exception exception, string action)
    {
        Exception = exception;
        Action = action;
    }
}